api:
    build: ./
    volumes:
      - ./:/usr/apps/api
    ports:
      - 8080:8080
    environment:
      - PORT=${PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
